### ISSUE TITLE
local variable 'num_bytes' referenced before assignment

### ISSUE THREAD

**Issue by moshix** [SYSPROG-JLS/S370BALAsm#1]
Hello and congrats again on this amazing assembler (and emulator!). 

I am compiling a very simple assembler report which produces a payroll report (as per my latest video). 

When assembling I get the below error which I can not understand. What does this mean?

thank you very much!

M

Step 1: Executing Pass 1 Logic
Traceback (most recent call last):
  File "/Users/moshe/S370BALAsm/S370BALAsm.py", line 896, in <module>
    (DS_num_bytes, const_array) = handle_DS(sl[15:50].rstrip(' '))
  File "/Users/moshe/S370BALAsm/S370BALAsm.py", line 437, in handle_DS
    byte_array = [ '40' for i in range(0,num_bytes) ]
UnboundLocalError: local variable 'num_bytes' referenced before assignment

**Comment by moshix** [comment]
Hey Jim

Small update: by looking at the assembler source code in Python, I think the assembler has difficulties understanding record definitions of the type:

PAYREC   DS    0CL80       HANDLE FOR THE STRUCTURE                                                                                   
EMPID    DS    CL4         EMPLOYEE ID                                 
         DS    CL6         FILLER TO POSITION 10                       
EMPLOYEE DS    CL21        NAME OF EMPLOYEE                            
         DS    CL2         FILLER TO POSITION 34                       
SALARY   DS    CL4         MONTHLY SALARY                              
TOEND    DS    CL43        80 BYTES SO FAR   

The 0CL80 is confusing it, I believe. 

Many thanks

M

**Comment by SYSPROG-JLS** [comment]
Hi Moshix,

You are correct. Currently, I am not handling that kind of a construct. A zero isn't permitted preceding any constant type. But seeing it is such a common construct, it should be included in the next release.

**Comment by moshix** [comment]
perfect! Thank you Jim. 

kind regards

M

**Comment by SYSPROG-JLS** [comment]
Fixed problem. Assembler will now accept statements like:
PAYREC      0DSCL80
or
LOOP         0H

**Comment by SYSPROG-JLS** [comment]
Hi Moshix,
1) I believe that I have gotten rid of the trace output when an error occurs in favor of meaningful error messages.
2) Give the PAYREC assemble a try again as code has been added to enable the 0DS  construct
Just download S370BALAsm.py before you test again

thanks!

Jim

**Comment by moshix** [comment]
thank you Jim! Much cleaner now! 

M

**Comment by moshix** [comment]
But I still get this:
Step 1: Executing Pass 1 Logic
Error at Line number: 40 - General Syntax Error
Source Code: PAYREC   DS    0CL80       HANDLE FOR THE STRUCTURE

**Comment by SYSPROG-JLS** [comment]
Hi M,
I get the same error if my comment does not start in the proper column.
Insure that your comment starts in col 51 or beyond. Code Must adhere to the following column requirements:
```
# 1     10       16       51
# Label Mnemonic Operands Comments
```
The initial spec said col 50 for comments - I'll need to fix the README.txt

**Comment by moshix** [comment]
thanks. One step further. Now this breaks on 

OUTAREA  DC    0CL133' '                                                                                                                     
EMPTY    DC    CL1' '                                                  
PEMPID   DS    CL4' '                                                  
         DC    CL6' '                                                  
PEMPLOYE DS    CL20' '                                                 
         DC    CL2' '                                                  
PDOLLAR  DC    CL1' '                                                  
PSALARY  DS    CL5' '                                                  
OFILLER  DC    CL94' '

**Comment by SYSPROG-JLS** [comment]
M,
Some observations based on my knowledge of IBM assembler coding:
DC's can't have the 0 in front of the CL - only DS's
Also DS'c can't attempt to define a literal - DS = define storage(only); DC = define constant

So based on the above, your code should look like this:

```
OUTAREA  DS    0CL133
EMPTY    DC    CL1' '
PEMPID   DC    CL4' '
         DC    CL6' '
PEMPLOYE DS    CL20
         DC    CL2' '
PDOLLAR  DC    CL1' '
PSALARY  DS    CL5
OFILLER  DC    CL94' '
```

**Comment by SYSPROG-JLS** [comment]
M,
OK, I stand corrected. 
It appears that IFOX00 on MVS3.8J does assemble your code cleanly:
```
                                     26 *                       
00012E                               27 OUTAREA  DC    0CL133' '
00012E 40                            28 EMPTY    DC    CL1' '   
00012F                               29 PEMPID   DS    CL4' '   
000133 404040404040                  30          DC    CL6' '   
000139                               31 PEMPLOYE DS    CL20' '  
00014D 4040                          32          DC    CL2' '   
00014F 40                            33 PDOLLAR  DC    CL1' '   
000150                               34 PSALARY  DS    CL5' '   
000155 4040404040404040              35 OFILLER  DC    CL94' '  
                                     36 *                       
                                         
                                         
NO STATEMENTS FLAGGED IN THIS ASSEMBLY   
HIGHEST SEVERITY WAS    0                
```
Hmm, this goes against what I was taught when I learned to code assembler.

I'm not sure I want to change my code to allow literals on DS statements nor allow the   DC   0CL133' '.

Not sure why IFOX00 would allow this. DS in my head should only allocate storage to a name. DC should do the same plus fill that with a certain value(s).  I do notice that on "PEMPID   DS    CL4' '" the assembler allows the single quotes but doesn't fill the storage with blanks.

**Comment by moshix** [comment]
Hello Jim

Yes, all the assemblers from FX, to Assembler H, to HLASM up to latest release all compile this without warnings. In the HLASM book by John Ehrman (rip) he has many examples of doing exactly that. 

Ultimately I am trying to get a report writer to assembler which I also show in my latest video. 

But if you prefer to not allow this syntax, that is of course completely your right to do so and I will adapt. 

Many thanks!

M

**Comment by SYSPROG-JLS** [comment]
Hello M,
Not sure of the rationale for not flagging that syntax with a warning. But I will certainly take your word that is indeed the case. I'll make a note of this, but for the time being I'd prefer to not allow this syntax.

If there is anything I can do to help you with this report writer you are trying to assemble just let me know, and thanks again for showcasing this in your next video!

Jim

**Comment by moshix** [comment]
JIm

can you kindly send me an email to moshix at gmail . com so I can forward you my little assembler program to see how we best get it to run on your emulator? It assembles now cleanly. 

Many thanks

M
